### ISSUE TITLE
Failed to run Quickstart

### ISSUE THREAD

**Issue by happyseone** [triton-inference-server/model_analyzer#108]
Hello, I'm new at Triton inference server.

Here's an explanation how I did.

1. Run Triton inference server first
docker run --gpus=1 --rm -p8000:8000 -p8001:8001 -p8002:8002 -v `pwd`/model_repository:/models nvcr.io/nvidia/tritonserver:20.11-py3 tritonserver --model-control-mode=explicit --model-repository=/models

Check that Triton server is working through IP_ADDRESS:8000/v2 on Postman
{
    "name": "triton",
    "version": "2.5.0",
    "extensions": [
        "classification",
        "sequence",
        "model_repository",
        "schedule_policy",
        "model_configuration",
        "system_shared_memory",
        "cuda_shared_memory",
        "binary_tensor_data",
        "statistics"
    ]
}

2. I followed the instruction on Quickstart of model-analyzer
model-analyzer -m /quick_start_repository -n add_sub --triton-launch-mode=remote --export-path=analysis_results

3. Error message was
`root@d1:/# model-analyzer -m /quick_start_repository -n add_sub --triton-launch-mode=remote --export-path=analysis_results
2021-04-05 05:32:45.685 INFO[entrypoint.py:288] Triton Model Analyzer started: config={'model_repository': '/quick_start_repository', 'model_names': [{'model_name': 'add_sub', 'objectives': {'perf_throughput': 10}, 'parameters': {'batch_sizes': [1], 'concurrency': []}}], 'objectives': {'perf_throughput': 10}, 'constraints': {}, 'batch_sizes': [1], 'concurrency': [], 'perf_analyzer_timeout': 600, 'perf_analyzer_cpu_util': 80.0, 'run_config_search_max_concurrency': 1024, 'run_config_search_max_instance_count': 5, 'run_config_search_disable': False, 'run_config_search_max_preferred_batch_size': 16, 'export': True, 'export_path': 'analysis_results', 'summarize': True, 'filename_model_inference': 'metrics-model-inference.csv', 'filename_model_gpu': 'metrics-model-gpu.csv', 'filename_server_only': 'metrics-server-only.csv', 'max_retries': 100, 'duration_seconds': 5, 'monitoring_interval': 0.01, 'client_protocol': 'grpc', 'perf_analyzer_path': 'perf_analyzer', 'perf_measurement_window': 5000, 'perf_output': False, 'triton_launch_mode': 'remote', 'triton_docker_image': 'nvcr.io/nvidia/tritonserver:21.02-py3', 'triton_http_endpoint': 'localhost:8000', 'triton_grpc_endpoint': 'localhost:8001', 'triton_metrics_url': 'http://localhost:8002/metrics', 'triton_server_path': 'tritonserver', 'triton_output_path': None, 'triton_server_flags': {}, 'log_level': 'INFO', 'gpus': ['all'], 'output_model_repository_path': './output_model_repository', 'override_output_model_repository': False, 'config_file': None, 'inference_output_fields': ['model_name', 'batch_size', 'concurrency', 'model_config_path', 'instance_group', 'dynamic_batch_sizes', 'satisfies_constraints', 'perf_throughput', 'perf_latency', 'cpu_used_ram'], 'gpu_output_fields': ['model_name', 'gpu_id', 'batch_size', 'concurrency', 'model_config_path', 'instance_group', 'dynamic_batch_sizes', 'satisfies_constraints', 'gpu_used_memory', 'gpu_utilization', 'gpu_power_usage'], 'server_output_fields': ['model_name', 'gpu_id', 'gpu_used_memory', 'gpu_utilization', 'gpu_power_usage'], 'plots': [{'name': 'throughput_v_latency', 'title': 'Throughput vs. Latency', 'x_axis': 'perf_latency', 'y_axis': 'perf_throughput', 'monotonic': True}, {'name': 'gpu_mem_v_latency', 'title': 'GPU Memory vs. Latency', 'x_axis': 'perf_latency', 'y_axis': 'gpu_used_memory', 'monotonic': False}], 'top_n_configs': 3}
2021-04-05 05:32:45.687 INFO[entrypoint.py:79] Using remote Triton Server...
2021-04-05 05:32:45.687 WARNING[entrypoint.py:82] GPU memory metrics reported in the remote mode are not accuracte. Model Analyzer uses Triton explicit model control to load/unload models. Some frameworks do not release the GPU memory even when the memory is not being used. Consider using the "local" or "docker" mode if you want to accurately monitor the GPU memory usage for different models.
2021-04-05 05:32:45.687 WARNING[entrypoint.py:89] Config sweep parameters are ignored in the "remote" mode because Model Analyzer does not have access to the model repository of the remote Triton Server.
2021-04-05 05:32:45.753 INFO[driver.py:236] init
2021-04-05 05:32:46.823 INFO[entrypoint.py:327] Starting perf_analyzer...
2021-04-05 05:32:46.823 INFO[analyzer.py:82] Profiling server only metrics...
2021-04-05 05:32:47.849 INFO[gpu_monitor.py:73] Using GPU(s) with UUID(s) = { GPU-c8fdb676-2c11-669a-4cff-f300b28eb26a } for the analysis.
2021-04-05 05:32:48.869 INFO[run_search.py:155] Will sweep only through the concurrency values...
2021-04-05 05:32:48.869 INFO[run_search.py:262] Concurrency set to 1.
2021-04-05 05:32:48.870 INFO[client.py:82] Model add_sub load failed: [StatusCode.INTERNAL] failed to load 'add_sub', no version is available
2021-04-05 05:32:53.922 INFO[client.py:143] Model readiness failed for model add_sub. Error None
Traceback (most recent call last):
  File "/usr/local/bin/model-analyzer", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/model_analyzer/entrypoint.py", line 328, in main
    analyzer.run()
  File "/usr/local/lib/python3.8/dist-packages/model_analyzer/analyzer.py", line 95, in run
    run_config_generator = RunConfigGenerator(
  File "/usr/local/lib/python3.8/dist-packages/model_analyzer/config/run/run_config_generator.py", line 65, in __init__
    self._generate_run_configs()
  File "/usr/local/lib/python3.8/dist-packages/model_analyzer/config/run/run_config_generator.py", line 290, in _generate_run_configs
    self._generate_run_config_for_model_sweep(
  File "/usr/local/lib/python3.8/dist-packages/model_analyzer/config/run/run_config_generator.py", line 229, in _generate_run_config_for_model_sweep
    model_config = ModelConfig.create_from_triton_api(
  File "/usr/local/lib/python3.8/dist-packages/model_analyzer/triton/model/model_config.py", line 111, in create_from_triton_api
    model_config_dict = client.get_model_config(model_name, num_retries)
  File "/usr/local/lib/python3.8/dist-packages/model_analyzer/triton/client/grpc_client.py", line 54, in get_model_config
    model_config_dict = self._client.get_model_config(model_name,
  File "/usr/local/lib/python3.8/dist-packages/tritonclient/grpc/__init__.py", line 476, in get_model_config
    raise_error_grpc(rpc_error)
  File "/usr/local/lib/python3.8/dist-packages/tritonclient/grpc/__init__.py", line 61, in raise_error_grpc
    raise get_error_grpc(rpc_error) from None
tritonclient.utils.InferenceServerException: [StatusCode.UNAVAILABLE] Request for unknown model: 'add_sub' has no available versions
`

I didn't change add_sub folder, so I have no idea what to do.

**Comment by happyseone** [comment]
Sorry, I just solved the problem.

**Comment by devloper13** [comment]
> Sorry, I just solved the problem.

It's always great to mention how you solvedyour problem so it can be helpful for others.
