### ISSUE TITLE
Quick start out of date

### ISSUE THREAD

**Issue by msaroufim** [triton-inference-server/model_analyzer#130]
Hi folks.

I'm trying to run the quick start instructions https://github.com/triton-inference-server/model_analyzer/blob/main/docs/quick_start.md

I have successfully installed triton server and the model_analyzer from the docker file

But I'm getting an error at this step 

`$ model-analyzer -m /quick_start_repository -n add_sub --triton-launch-mode=local --export-path=analysis_results`

Where the error looks like

`2021-04-30 22:06:37.785 INFO[client.py:82] Model add_sub_i34 load failed: [StatusCode.UNAVAILABLE] explicit model load / unload is not allowed if polling is enabled
2021-04-30 22:06:37.785 INFO[analyzer_state_manager.py:140] Saved checkpoint to analysis_results/checkpoints/0.ckpt.`

And then finally fails at this step

`
  File "/usr/local/bin/model-analyzer", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/model_analyzer/entrypoint.py", line 233, in main
    analyzer.run()
  File "/usr/local/lib/python3.8/dist-packages/model_analyzer/analyzer.py", line 116, in run
    self._result_manager.collect_and_sort_results(
  File "/usr/local/lib/python3.8/dist-packages/model_analyzer/result/result_manager.py", line 309, in collect_and_sort_results
    result_dict = results[model_name]
KeyError: 'add_sub'
`

`analysis_results/` and `output_model_repository` seem to be correctly filled out with directories for the results and variationss of `add_sub` respectively

Here is the full log error https://gist.github.com/msaroufim/912ab9a5ae17b5ed444bf790ead0612e

**Comment by aramesh7** [comment]
@msaroufim There is a fix for this #129 currently running in our CI. It should be merged by the end of the day. Sorry for the inconvenience.

**Comment by msaroufim** [comment]
Sweet thank you! I'll check it out again on Monday and close this issue for now

**Comment by msaroufim** [comment]
Hi @aramesh7 opening this again - I pulled the changes, rebuilt the image and now getting the below indexing error as well

https://gist.github.com/msaroufim/62512953e87e29e234cc0c28dc55f69f

`
best_config = sorted_measurements[0][0]
IndexError: list index out of range
`

Also uploading a screenshot of the GPU utilization for the add_sub example, I'm curious how come the GPU utilization is 0% even though the memory and power are non zero. Is this instantiating some data loader on the GPU that's not doing much work?

![Screen Shot 2021-05-03 at 11 12 39 AM](https://user-images.githubusercontent.com/3282513/116915132-7b16c780-ac00-11eb-9a34-1e29d77566b1.png)

**Comment by aramesh7** [comment]
@msaroufim It seems like your `add_sub` model did not load at all, and as such did not generate any inference results. The results you see in the `Server Only` table are for measurements taken of the Triton Server, which doesn't utilize the GPU. Make sure that if you are using the docker triton launch mode, the output model repository path is mounted to the same absolute path inside and outside the model analyzer container.

**Comment by msaroufim** [comment]
Thank you!

I am running the container by following the instructions to the letter here ,Step 1 and Step 2 https://github.com/triton-inference-server/model_analyzer/blob/main/docs/quick_start.md#step-1-install-model-analyzer-and-run-container

For installing I followed the instructions in part 2 where I setup the image from a Dockerfile https://github.com/triton-inference-server/model_analyzer/blob/main/docs/install.md

Here are the contents quick_start inside the container

```
root@ip-172-31-1-60:/opt/triton-model-analyzer/examples# ls
quick-start
root@ip-172-31-1-60:/opt/triton-model-analyzer/examples# cd quick-start/
root@ip-172-31-1-60:/opt/triton-model-analyzer/examples/quick-start# ls
add_sub
root@ip-172-31-1-60:/opt/triton-model-analyzer/examples/quick-start# cd add_sub/
root@ip-172-31-1-60:/opt/triton-model-analyzer/examples/quick-start/add_sub# ls
1  config.pbtxt  output0_labels.txt
root@ip-172-31-1-60:/opt/triton-model-analyzer/examples/quick-start/add_sub# 
```

Outside the container on my host EC2 machine

```
ubuntu@ip-172-31-1-60:~/model_analyzer/examples$ ls
quick-start
ubuntu@ip-172-31-1-60:~/model_analyzer/examples$ cd quick-start/
ubuntu@ip-172-31-1-60:~/model_analyzer/examples/quick-start$ ls
add_sub
ubuntu@ip-172-31-1-60:~/model_analyzer/examples/quick-start$ cd add_sub/
ubuntu@ip-172-31-1-60:~/model_analyzer/examples/quick-start/add_sub$ ls
1  config.pbtxt  output0_labels.txt
ubuntu@ip-172-31-1-60:~/model_analyzer/examples/quick-start/add_sub$ echo $HOME
/home/ubuntu
ubuntu@ip-172-31-1-60:~/model_analyzer/examples/quick-start/add_sub$ pwd
/home/ubuntu/model_analyzer/examples/quick-start/add_sub
ubuntu@ip-172-31-1-60:~/model_analyzer/examples/quick-start/add_sub$ 
```

**Comment by aramesh7** [comment]
@msaroufim Sorry for the confusion surrounding launching the model analyzer. Are you running MA from `/opt/triton-model-analyzer`? Is model analyzer able to read and write from `./output_model_repository` inside the container? If not, try `chmod -R 777 ./output_model_repository` and run  again.

**Comment by msaroufim** [comment]
> @msaroufim Sorry for the confusion surrounding launching the model analyzer. Are you running MA from `/opt/triton-model-analyzer`?

Yep

> Is model analyzer able to read and write from `./output_model_repository` inside the container? If not, try `chmod -R 777 ./output_model_repository` and run again.

Just did, same issue

In case this helps `output_model_repository` is not empty 

```
root@ip-172-31-1-60:/opt/triton-model-analyzer/output_model_repository/add_sub_i0# ls
config.pbtxt
root@ip-172-31-1-60:/opt/triton-model-analyzer/output_model_repository/add_sub_i0# cd ..
root@ip-172-31-1-60:/opt/triton-model-analyzer/output_model_repository# ls
add_sub_i0  add_sub_i10  add_sub_i12  add_sub_i14  add_sub_i16  add_sub_i18  add_sub_i2   add_sub_i21  add_sub_i23  add_sub_i25  add_sub_i27  add_sub_i29  add_sub_i30  add_sub_i32  add_sub_i34  add_sub_i5  add_sub_i7  add_sub_i9
add_sub_i1  add_sub_i11  add_sub_i13  add_sub_i15  add_sub_i17  add_sub_i19  add_sub_i20  add_sub_i22  add_sub_i24  add_sub_i26  add_sub_i28  add_sub_i3   add_sub_i31  add_sub_i33  add_sub_i4   add_sub_i6  add_sub_i8
```

**Comment by aramesh7** [comment]
Inside the container could you try `tritonserver  --model-control-mode explicit --load-model add_sub_i0 --model-repository /opt/triton-model-analyzer/output_model_repository/` to see what Triton says? You can paste the log here as well.

**Comment by msaroufim** [comment]
Here you go. I also verified that triton-server is available and healthy by following instructions here https://github.com/triton-inference-server/server/blob/master/docs/quickstart.md 

```
ubuntu@ip-172-31-1-60:~$ docker run -it --rm --gpus all \
>         -v /var/run/docker.sock:/var/run/docker.sock \
>         -v $HOME/model_analyzer/examples/quick-start:/quick_start_repository \
>         --net=host --name model-analyzer \
>         model-analyzer /bin/bash
root@ip-172-31-1-60:/opt/triton-model-analyzer# mkdir analysis_results
root@ip-172-31-1-60:/opt/triton-model-analyzer# tritonserver --model-control-mode explicit --load-model add_sub_i0 --model-repository /opt/triton-model-analyzer/output_model_repository/
I0504 17:04:12.265865 29 metrics.cc:228] Collecting metrics for GPU 0: Tesla K80
I0504 17:04:12.276581 29 metrics.cc:228] Collecting metrics for GPU 1: Tesla K80
I0504 17:04:12.284589 29 metrics.cc:228] Collecting metrics for GPU 2: Tesla K80
I0504 17:04:12.292757 29 metrics.cc:228] Collecting metrics for GPU 3: Tesla K80
I0504 17:04:12.301129 29 metrics.cc:228] Collecting metrics for GPU 4: Tesla K80
I0504 17:04:12.309696 29 metrics.cc:228] Collecting metrics for GPU 5: Tesla K80
I0504 17:04:12.318484 29 metrics.cc:228] Collecting metrics for GPU 6: Tesla K80
I0504 17:04:12.327465 29 metrics.cc:228] Collecting metrics for GPU 7: Tesla K80
I0504 17:04:13.633383 29 libtorch.cc:932] TRITONBACKEND_Initialize: pytorch
I0504 17:04:13.633424 29 libtorch.cc:942] Triton TRITONBACKEND API version: 1.0
I0504 17:04:13.633441 29 libtorch.cc:948] 'pytorch' TRITONBACKEND API version: 1.0
2021-05-04 17:04:14.177303: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
W0504 17:04:14.331032 29 metrics.cc:329] failed to get energy consumption for GPU 0: Not Supported
W0504 17:04:14.335026 29 metrics.cc:329] failed to get energy consumption for GPU 1: Not Supported
W0504 17:04:14.339051 29 metrics.cc:329] failed to get energy consumption for GPU 2: Not Supported
W0504 17:04:14.343073 29 metrics.cc:329] failed to get energy consumption for GPU 3: Not Supported
W0504 17:04:14.347029 29 metrics.cc:329] failed to get energy consumption for GPU 4: Not Supported
W0504 17:04:14.350990 29 metrics.cc:329] failed to get energy consumption for GPU 5: Not Supported
W0504 17:04:14.354974 29 metrics.cc:329] failed to get energy consumption for GPU 6: Not Supported
W0504 17:04:14.358906 29 metrics.cc:329] failed to get energy consumption for GPU 7: Not Supported
I0504 17:04:14.650635 29 tensorflow.cc:2165] TRITONBACKEND_Initialize: tensorflow
I0504 17:04:14.650666 29 tensorflow.cc:2175] Triton TRITONBACKEND API version: 1.0
I0504 17:04:14.650681 29 tensorflow.cc:2181] 'tensorflow' TRITONBACKEND API version: 1.0
I0504 17:04:14.650695 29 tensorflow.cc:2205] backend configuration:
{}
I0504 17:04:14.701522 29 onnxruntime.cc:1722] TRITONBACKEND_Initialize: onnxruntime
I0504 17:04:14.702805 29 onnxruntime.cc:1732] Triton TRITONBACKEND API version: 1.0
I0504 17:04:14.702821 29 onnxruntime.cc:1738] 'onnxruntime' TRITONBACKEND API version: 1.0
I0504 17:04:14.831017 29 openvino.cc:1168] TRITONBACKEND_Initialize: openvino
I0504 17:04:14.831040 29 openvino.cc:1178] Triton TRITONBACKEND API version: 1.0
I0504 17:04:14.831056 29 openvino.cc:1184] 'openvino' TRITONBACKEND API version: 1.0
I0504 17:04:15.099863 29 pinned_memory_manager.cc:206] Pinned memory pool is created at '0x2030c0000' with size 268435456
I0504 17:04:15.127700 29 tritonserver.cc:1658] 
+----------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Option                           | Value                                                                                                                                                                                  |
+----------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| server_id                        | triton                                                                                                                                                                                 |
| server_version                   | 2.9.0                                                                                                                                                                                  |
| server_extensions                | classification sequence model_repository model_repository(unload_dependents) schedule_policy model_configuration system_shared_memory cuda_shared_memory binary_tensor_data statistics |
| model_repository_path[0]         | /opt/triton-model-analyzer/output_model_repository/                                                                                                                                    |
| model_control_mode               | MODE_EXPLICIT                                                                                                                                                                          |
| startup_models_0                 | add_sub_i0                                                                                                                                                                             |
| strict_model_config              | 1                                                                                                                                                                                      |
| pinned_memory_pool_byte_size     | 268435456                                                                                                                                                                              |
| min_supported_compute_capability | 6.0                                                                                                                                                                                    |
| strict_readiness                 | 1                                                                                                                                                                                      |
| exit_timeout                     | 30                                                                                                                                                                                     |
+----------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

I0504 17:04:15.127750 29 server.cc:231] No server context available. Exiting immediately.
error: creating server: Internal - failed to stat file /opt/triton-model-analyzer/output_model_repository/
W0504 17:04:16.362307 29 metrics.cc:329] failed to get energy consumption for GPU 0: Not Supported
W0504 17:04:16.365432 29 metrics.cc:329] failed to get energy consumption for GPU 1: Not Supported
W0504 17:04:16.368699 29 metrics.cc:329] failed to get energy consumption for GPU 2: Not Supported
W0504 17:04:16.371958 29 metrics.cc:329] failed to get energy consumption for GPU 3: Not Supported
W0504 17:04:16.375316 29 metrics.cc:329] failed to get energy consumption for GPU 4: Not Supported
W0504 17:04:16.378517 29 metrics.cc:329] failed to get energy consumption for GPU 5: Not Supported
W0504 17:04:16.381652 29 metrics.cc:329] failed to get energy consumption for GPU 6: Not Supported
W0504 17:04:16.384763 29 metrics.cc:329] failed to get energy consumption for GPU 7: Not Supported
E0504 17:04:16.419304 29 cuda_memory_manager.cc:66] Failed to finalize CUDA memory manager: [3] CNMEM_STATUS_NOT_INITIALIZED
```

**Comment by Tabrizian** [comment]
@msaroufim From your logs,  it looks like it failed to load the model:

```
error: creating server: Internal - failed to stat file /opt/triton-model-analyzer/output_model_repository/
W0504 17:04:16.362307 29 metrics.cc:329] failed to get energy consumption for GPU 0: Not Supported
W0504 17:04:16.365432 29 metrics.cc:329] failed to get energy consumption for GPU 1: Not Supported
W0504 17:04:16.368699 29 metrics.cc:329] failed to get energy consumption for GPU 2: Not Supported
W0504 17:04:16.371958 29 metrics.cc:329] failed to get energy consumption for GPU 3: Not Supported
W0504 17:04:16.375316 29 metrics.cc:329] failed to get energy consumption for GPU 4: Not Supported
W0504 17:04:16.378517 29 metrics.cc:329] failed to get energy consumption for GPU 5: Not Supported
W0504 17:04:16.381652 29 metrics.cc:329] failed to get energy consumption for GPU 6: Not Supported
W0504 17:04:16.384763 29 metrics.cc:329] failed to get energy consumption for GPU 7: Not Supported
E0504 17:04:16.419304 29 cuda_memory_manager.cc:66] Failed to finalize CUDA memory manager: [3] CNMEM_STATUS_NOT_INITIALIZED
```

**Comment by msaroufim** [comment]
Thanks @Tabrizian, I'm still confused why that's the case though

The output_model_repo is getting filled out

`
root@ip-172-31-1-60:/opt/triton-model-analyzer/output_model_repository# ls
add_sub_i0  add_sub_i10  add_sub_i12  add_sub_i14  add_sub_i16  add_sub_i18  add_sub_i2   add_sub_i21  add_sub_i23  add_sub_i25  add_sub_i27  add_sub_i29  add_sub_i30  add_sub_i32  add_sub_i34  add_sub_i5  add_sub_i7  add_sub_i9
add_sub_i1  add_sub_i11  add_sub_i13  add_sub_i15  add_sub_i17  add_sub_i19  add_sub_i20  add_sub_i22  add_sub_i24  add_sub_i26  add_sub_i28  add_sub_i3   add_sub_i31  add_sub_i33  add_sub_i4   add_sub_i6  add_sub_i8
`

**Comment by aramesh7** [comment]
@msaroufim what is the output of `ls -al /opt/triton-model-analyzer/output_model_repository`, I can only think of a permission error if you're running on launch model local.

**Comment by msaroufim** [comment]
Here is the before and after

```
root@ip-172-31-1-60:/opt/triton-model-analyzer# ls -al /opt/triton-model-analyzer/output_model_repository
total 148
...
rwxr-xr-x  2 root root 4096 May  4 19:48 add_sub_i5
drwxr-xr-x  2 root root 4096 May  4 19:48 add_sub_i6
drwxr-xr-x  2 root root 4096 May  4 19:48 add_sub_i7
drwxr-xr-x  2 root root 4096 May  4 19:48 add_sub_i8
drwxr-xr-x  2 root root 4096 May  4 19:48 add_sub_i9

root@ip-172-31-1-60:/opt/triton-model-analyzer# chmod -R 777 ./output_model_repository
root@ip-172-31-1-60:/opt/triton-model-analyzer# ls -al /opt/triton-model-analyzer/output_model_repository
total 148
drwxrwxrwx 37 root root 4096 May  4 19:50 .
drwxr-xr-x  1 root root 4096 May  4 19:47 ..
drwxrwxrwx  2 root root 4096 May  4 19:47 add_sub_i0
drwxrwxrwx  2 root root 4096 May  4 19:47 add_sub_i1
drwxrwxrwx  2 root root 4096 May  4 19:48 add_sub_i10
drwxrwxrwx  2 root root 4096 May  4 19:48 add_sub_i11
```

Then tried


```
root@ip-172-31-1-60:/opt/triton-model-analyzer# model-analyzer -m /quick_start_repository -n add_sub --triton-launch-mode=local --export-path=analysis_results --output-model-repository-path=/opt/triton-model-analyzer/output_model_repository

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/model-analyzer", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/model_analyzer/entrypoint.py", line 222, in main
    analyzer = Analyzer(config, metric_tags, client, server, state_manager)
  File "/usr/local/lib/python3.8/dist-packages/model_analyzer/analyzer.py", line 68, in __init__
    self._model_manager = ModelManager(
  File "/usr/local/lib/python3.8/dist-packages/model_analyzer/model_manager.py", line 71, in __init__
    raise TritonModelAnalyzerException(
model_analyzer.model_analyzer_exceptions.TritonModelAnalyzerException: Path "/opt/triton-model-analyzer/output_model_repository" already exists. Please set or modify "--output-model-repository-path" flag or remove this directory. You can also allow overriding of the output directory using the "--override-output-model-repository" flag.

```

**Comment by aramesh7** [comment]
@msaroufim Could you add the '--override-output-model-repository`.

**Comment by msaroufim** [comment]
I did but it had no effect

**Comment by aramesh7** [comment]
Yes, we have updated the interface for the upcoming 21.05 release. We will be updating the docs today and next week. Sorry for the confusion.  You can try
```
$ model-analyzer profile -m /quick_start_repository --profile-models add_sub
.
.
.
$ model-analyzer analyze --analysis-models add_sub -e analysis_results
```

**Comment by msaroufim** [comment]
It's working! So I was working with Triton 21.04 on K80 but when I switched over to a V100 everything started working. 

I found p3.2xlarge available on AWS today - that p3.8x shortage :'(
