### ISSUE TITLE
Model Analyzer failing with TypeError: sum() takes no keyword arguments

### ISSUE THREAD

**Issue by aishanibhalla** [triton-inference-server/model_analyzer#431]
Hi, I'm trying to run the model analyzer on a pre-trained transformer model in onnx format. 

I ran the following command for running model-analyzer:

`model-analyzer profile --model-repository ./models/outer/triton --profile-models bart_model --triton-launch-mode=docker --override-output-model-repository --output-model-repository /data/workspace/summarization/model_analyzer_output/model_output`

model analyzer error logs:

```
[Model Analyzer] Initiliazing GPUDevice handles
[Model Analyzer] Using GPU 0 Tesla V100-PCIE-16GB with UUID GPU-f03434e8-b9ef-102e-ed20-34bd49886aae
[Model Analyzer] Using GPU 1 Tesla V100-PCIE-16GB with UUID GPU-597a01a5-036c-2984-52f7-bbb176645942
[Model Analyzer] Using GPU 2 Tesla V100-PCIE-16GB with UUID GPU-08063e25-7684-6d0e-0628-7f47c4690537
[Model Analyzer] Using GPU 3 Tesla V100-PCIE-16GB with UUID GPU-f469625e-5978-d898-844a-145c8287db0e
[Model Analyzer] WARNING: Overriding the output model repo path "/data/workspace/summarization/model_analyzer_output/model_output"
[Model Analyzer] Starting a Triton Server using docker
[Model Analyzer] No checkpoint file found, starting a fresh run.
[Model Analyzer] Profiling server only metrics...
[Model Analyzer] Stopped Triton Server.
Traceback (most recent call last):
  File "/opt/miniconda/bin/model-analyzer", line 8, in <module>
    sys.exit(main())
  File "/opt/miniconda/lib/python3.7/site-packages/model_analyzer/entrypoint.py", line 386, in main
    analyzer.profile(client=client, gpus=gpus)
  File "/opt/miniconda/lib/python3.7/site-packages/model_analyzer/analyzer.py", line 96, in profile
    self._get_server_only_metrics(client)
  File "/opt/miniconda/lib/python3.7/site-packages/model_analyzer/analyzer.py", line 199, in _get_server_only_metrics
    self._metrics_manager.profile_server()
  File "/opt/miniconda/lib/python3.7/site-packages/model_analyzer/record/metrics_manager.py", line 165, in profile_server
    server_gpu_metrics = self._get_gpu_inference_metrics()
  File "/opt/miniconda/lib/python3.7/site-packages/model_analyzer/record/metrics_manager.py", line 484, in _get_gpu_inference_metrics
    self._gpu_metrics, lambda record: record.device_uuid())
  File "/opt/miniconda/lib/python3.7/site-packages/model_analyzer/record/record_aggregator.py", line 171, in groupby
    ]).aggregate(record_types=[record_type])
  File "/opt/miniconda/lib/python3.7/site-packages/model_analyzer/record/record_aggregator.py", line 233, in aggregate
    for record_type in record_types
  File "/opt/miniconda/lib/python3.7/site-packages/model_analyzer/record/record_aggregator.py", line 233, in <dictcomp>
    for record_type in record_types
  File "/opt/miniconda/lib/python3.7/site-packages/model_analyzer/record/types/gpu_utilization.py", line 50, in average
    return sum(seq[1:], start=seq[0]) / len(seq)
TypeError: sum() takes no keyword arguments
```

**Comment by nv-braf** [comment]
@aishanibhalla I see that you are using Python 3.7, and the sum() start keyword was added in version 3.8. Can you try running with python 3.8 and see if that fixes the problem?
