### ISSUE TITLE
Can't support dcgm 3.0

### ISSUE THREAD

**Issue by fsatka** [triton-inference-server/model_analyzer#544]
After instalation dcgm by this [manual](https://docs.nvidia.com/datacenter/dcgm/latest/user-guide/getting-started.html#installation) started getting errors:
```
[Model Analyzer] Initializing GPUDevice handles
Traceback (most recent call last):
  File "/home/radoronin/anaconda3/lib/python3.9/site-packages/model_analyzer/monitor/dcgm/dcgm_structs.py", line 622, in _LoadDcgmLibrary
    dcgmLib = CDLL(os.path.join(libDcgmPath,
  File "/home/radoronin/anaconda3/lib/python3.9/ctypes/__init__.py", line 382, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /usr/lib/x86_64-linux-gnu/libdcgm.so.2: cannot open shared object file: No such file or directory
```

**DCGM Version : 3.0.4**

Then i create symlink _libdcgm.so.2_ to _libdcgm.so_, and then errors changed to:
```
[Model Analyzer] Initializing GPUDevice handles
Traceback (most recent call last):
  File "/home/radoronin/anaconda3/bin/model-analyzer", line 8, in <module>
    sys.exit(main())
  File "/home/radoronin/anaconda3/lib/python3.9/site-packages/model_analyzer/entrypoint.py", line 248, in main
    gpus = GPUDeviceFactory().verify_requested_gpus(config.gpus)
  File "/home/radoronin/anaconda3/lib/python3.9/site-packages/model_analyzer/device/gpu_device_factory.py", line 36, in __init__
    self.init_all_devices()
  File "/home/radoronin/anaconda3/lib/python3.9/site-packages/model_analyzer/device/gpu_device_factory.py", line 62, in init_all_devices
    device_atrributes = dcgm_agent.dcgmGetDeviceAttributes(
  File "/home/radoronin/anaconda3/lib/python3.9/site-packages/model_analyzer/monitor/dcgm/dcgm_agent.py", line 103, in dcgmGetDeviceAttributes
    dcgm_structs._dcgmCheckReturn(ret)
  File "/home/radoronin/anaconda3/lib/python3.9/site-packages/model_analyzer/monitor/dcgm/dcgm_structs.py", line 646, in _dcgmCheckReturn
    raise DCGMError(ret)
model_analyzer.monitor.dcgm.dcgm_structs.DCGMError_VerMismatch: API version mismatch
```

And i cant find in official docs how to install DCGM of early version.

**Comment by nv-braf** [comment]
In our container we use: 
```
# DCGM version to install for Model Analyzer
ENV DCGM_VERSION=2.2.9
```

Can you try installing that version?
```apt-get install -y datacenter-gpu-manager=1:${DCGM_VERSION}```

**Comment by fsatka** [comment]
thanks, that's work for me!
