### ISSUE TITLE
Error when start triton server.

### ISSUE THREAD

**Issue by qianwangn** [triton-inference-server/model_analyzer#56]
@igobypenn 
The model.plan is convert in 20.11.py3 container, I can start the model with 20.11.py3 container,but can not load models with model_analyzer container.

Notice: I modify some code to print the error message.

when I run `model-analyzer -m /workspace/examples/ -n fcos_lift_6c`

`root@2fb036737861:/workspace/examples/fcos_lift_6c# model-analyzer -m /workspace/examples/ -n fcos_lift_6c --triton-launch-mode local
2020-12-29 11:41:44.849 INFO[entrypoint.py:360] Triton Model Analyzer started Namespace(batch_sizes='1', client_protocol='grpc', concurrency='1', duration_seconds=5, export=False, export_path='.', filename_model='metrics-model.csv', filename_server_only='metrics-server-only.csv', gpus=['all'], log_level='INFO', max_retries=100, model_names='fcos_lift_6c', model_repository='/workspace/examples/', monitoring_interval=0.01, perf_analyzer_path='perf_analyzer', triton_grpc_endpoint='localhost:8001', triton_http_endpoint='localhost:8000', triton_launch_mode='local', triton_metrics_url='http://localhost:8002/metrics', triton_output_path=None, triton_server_path='tritonserver', triton_version='20.11-py3') arguments
2020-12-29 11:41:44.854 INFO[entrypoint.py:93] Starting a local Triton Server...
2020-12-29 11:41:44.863 INFO[server_local.py:62] Triton Server started.
2020-12-29 11:41:44.867 INFO[entrypoint.py:208] Triton Server is ready.
2020-12-29 11:41:44.868 INFO[driver.py:236] init
2020-12-29 11:41:45.982 INFO[analyzer.py:87] Profiling server only metrics...
2020-12-29 11:41:47.20 INFO[monitor.py:74] Using GPU(s) with UUID(s) = { GPU-a09e2347-cecb-8a34-a15d-50641a837031 } for the analysis.
Traceback (most recent call last):
  File "/opt/triton-model-analyzer/model_analyzer/triton/client/client.py", line 79, in load_model
    self._client.load_model(model.name())
  File "/usr/local/lib/python3.6/dist-packages/tritonclient/grpc/__init__.py", line 555, in load_model
    raise_error_grpc(rpc_error)
  File "/usr/local/lib/python3.6/dist-packages/tritonclient/grpc/__init__.py", line 61, in raise_error_grpc
    raise get_error_grpc(rpc_error) from None
tritonclient.utils.InferenceServerException: [StatusCode.INTERNAL] failed to load 'fcos_lift_6c', no version is available

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/model-analyzer", line 33, in <module>
    sys.exit(load_entry_point('nvidia-triton-model-analyzer', 'console_scripts', 'model-analyzer')())
  File "/opt/triton-model-analyzer/model_analyzer/entrypoint.py", line 366, in main
    run_analyzer(args, analyzer, client, run_configs)
  File "/opt/triton-model-analyzer/model_analyzer/entrypoint.py", line 318, in run_analyzer
    client.load_model(model=model)
  File "/opt/triton-model-analyzer/model_analyzer/triton/client/client.py", line 82, in load_model
    f"Unable to load the model : {e}")
model_analyzer.model_analyzer_exceptions.TritonModelAnalyzerException: Unable to load the model : [StatusCode.INTERNAL] failed to load 'fcos_lift_6c', no version is available`

**Comment by Tabrizian** [comment]
Thanks for the report.

@qianwangn Does starting the Triton Server work inside the container too (i.e. `tritonserver /workspace/examples/`? Can you please share the output of `tree /workspace/examples` here?

**Comment by qianwangn** [comment]
sorry, this problem is fixed, due to the config.pbtxt is wrong.
