### ISSUE TITLE
can't modify triton docker container in model analyzer

### ISSUE THREAD

**Issue by katerinafrid** [triton-inference-server/model_analyzer#582]
I want to run model_analyzer with triton in docker mode, also I need to install torch to load a model on triton server, but I don't see any option to install any package to triton container.

Error:
[Model Analyzer] Model nlu_model_config_2 load failed: [StatusCode.INVALID_ARGUMENT] load failed for model 'nlu_model_config_2': version 1: Internal: ModuleNotFoundError: No module named 'torch'

Command that I use:

```docker run -it --rm --gpus all -v /var/run/docker.sock:/var/run/docker.sock -v /home/kate/projects/monorepo/model_repository:/home/kate/projects/monorepo/model_repository -v /home/kate/projects/monorepo/new_output_model_analyzer:/home/kate/projects/monorepo/new_output_model_analyzer --net=host --name model-analyzer nvcr.io/nvidia/tritonserver:22.04-py3-sdk```

```model-analyzer -v profile  --override-output-model-repository --output-model-repository /home/kate/projects/monorepo/new_output_model_analyzer/new_output_model -f test.yaml ```

```model_repository: /home/kate/projects/monorepo/model_repository
triton_launch_mode: 'docker'

num-configs-per-model: 3

profile_models:
  nlu_model:
    parameters:
      batch_sizes: 1, 2, 4, 6, 8, 16, 32
    model_config_parameters:
      dynamic_batching:
        max_queue_delay_microseconds: [ 100, 200, 500, 1000 ]
      instance_group:
        - kind: KIND_GPU
          count: [ 1, 2 ]

concurrency:
  - 2
  - 4
  - 8

perf_analyzer_flags:
  percentile: 95
  measurement-mode: time_windows
  shape:
      - INPUT__0:128
      - INPUT__1:128
  input-data: zero
  latency-report-file: /workspace/latency_report.yaml 
```

If I set --triton-docker-image to the name of the image built from the following dockerfile:
```
FROM nvcr.io/nvidia/tritonserver:22.04-py3

ENV LC_ALL="C.UTF-8"
ENV LANG="en_US.UTF-8"

RUN pip install --upgrade pip && pip install torch==1.12.0+cu116 torchvision==0.13.0+cu116 torchaudio==0.12.0 --extra-index-url https://download.pytorch.org/whl/cu116
RUN pip install transformers

COPY ./model_repository /models

```
It gives me the following error 

```Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/model_analyzer/triton/client/client.py", line 49, in wait_for_server_ready
    if self._client.is_server_ready():
  File "/usr/local/lib/python3.8/dist-packages/tritonclient/grpc/__init__.py", line 339, in is_server_ready
    raise_error_grpc(rpc_error)
  File "/usr/local/lib/python3.8/dist-packages/tritonclient/grpc/__init__.py", line 62, in raise_error_grpc
    raise get_error_grpc(rpc_error) from None
tritonclient.utils.InferenceServerException: [StatusCode.UNAVAILABLE] failed to connect to all addresses
```

**Comment by katerinafrid** [comment]
actually it started working after I've added 
```

CMD tritonserver --model-repository=/models --model-control-mode=explicit --log-verbose 1
```
to the end of the Dockerfile
