### ISSUE TITLE
Model analyzer not picking up models within model repository

### ISSUE THREAD

**Issue by rohitgr7** [triton-inference-server/model_analyzer#625]
trying to use model analyzer (r22.08) but getting some issues:

this is the structure
```console
├── Dockerfile
├── models
│   └── classifier_python
│       ├── 1
│       │   └── model.py
│       └── config.pbtxt
├── requirements.txt
├── sweep.yaml
```

Error
```console
root@3090:/workspace# model-analyzer profile -f sweep.yaml 
[Model Analyzer] Initializing GPUDevice handles
[Model Analyzer] Using GPU 0 NVIDIA GeForce RTX 3090 with UUID GPU-ea4f9ae8-f9eb-1ecc-1576-e9301f674d25
[Model Analyzer] Starting a local Triton Server
[Model Analyzer] No checkpoint file found, starting a fresh run.
[Model Analyzer] Profiling server only metrics...
[Model Analyzer] 
[Model Analyzer] Creating model config: classifier_python_config_default
[Model Analyzer] 
[Model Analyzer] Model classifier_python_config_default load failed: [StatusCode.CANCELLED] CANCELLED
[Model Analyzer] 
[Model Analyzer] Creating model config: classifier_python_config_0
[Model Analyzer]   Setting instance_group to [{'count': 1, 'kind': 'KIND_GPU'}]
[Model Analyzer]   Setting max_batch_size to 1
[Model Analyzer]   Enabling dynamic_batching
[Model Analyzer] 
[Model Analyzer] Model classifier_python_config_0 load failed: [StatusCode.CANCELLED] CANCELLED
[Model Analyzer] 
[Model Analyzer] Creating model config: classifier_python_config_1
[Model Analyzer]   Setting instance_group to [{'count': 2, 'kind': 'KIND_GPU'}]
[Model Analyzer]   Setting max_batch_size to 1
[Model Analyzer]   Enabling dynamic_batching
[Model Analyzer] 
[Model Analyzer] Model classifier_python_config_1 load failed: [StatusCode.CANCELLED] CANCELLED
[Model Analyzer] 
[Model Analyzer] Creating model config: classifier_python_config_2
[Model Analyzer]   Setting instance_group to [{'count': 3, 'kind': 'KIND_GPU'}]
[Model Analyzer]   Setting max_batch_size to 1
[Model Analyzer]   Enabling dynamic_batching
[Model Analyzer] 
[Model Analyzer] Model classifier_python_config_2 load failed: [StatusCode.CANCELLED] CANCELLED
[Model Analyzer] 
[Model Analyzer] Creating model config: classifier_python_config_3
[Model Analyzer]   Setting instance_group to [{'count': 4, 'kind': 'KIND_GPU'}]
[Model Analyzer]   Setting max_batch_size to 1
[Model Analyzer]   Enabling dynamic_batching
[Model Analyzer] 
[Model Analyzer] Model classifier_python_config_3 load failed: [StatusCode.UNAVAILABLE] failed to connect to all addresses
[Model Analyzer] 
[Model Analyzer] Creating model config: classifier_python_config_4
[Model Analyzer]   Setting instance_group to [{'count': 5, 'kind': 'KIND_GPU'}]
[Model Analyzer]   Setting max_batch_size to 1
[Model Analyzer]   Enabling dynamic_batching
[Model Analyzer] 
[Model Analyzer] Model classifier_python_config_4 load failed: [StatusCode.CANCELLED] CANCELLED
[Model Analyzer] Saved checkpoint to /workspace/checkpoints/0.ckpt
[Model Analyzer] Profile complete. Profiled 0 configurations for models: []
[Model Analyzer] 
[Model Analyzer] ERROR: No results found for model: classifier_python
Traceback (most recent call last):
  File "/usr/local/bin/model-analyzer", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/model_analyzer/entrypoint.py", line 264, in main
    analyzer.profile(client=client,
  File "/usr/local/lib/python3.8/dist-packages/model_analyzer/analyzer.py", line 116, in profile
    self._analyze_models()
  File "/usr/local/lib/python3.8/dist-packages/model_analyzer/analyzer.py", line 248, in _analyze_models
    self._result_manager.compile_and_sort_results()
  File "/usr/local/lib/python3.8/dist-packages/model_analyzer/result/result_manager.py", line 140, in compile_and_sort_results
    self._add_results_to_heaps()
  File "/usr/local/lib/python3.8/dist-packages/model_analyzer/result/result_manager.py", line 325, in _add_results_to_heaps
    raise TritonModelAnalyzerException(
model_analyzer.model_analyzer_exceptions.TritonModelAnalyzerException: The model classifier_python was not found in the loaded checkpoint.
```

sweep
```
model_repository: models/

profile_models:
  classifier_python:
    objectives:     
      - perf_throughput
      - gpu_used_memory
    constraints:  
      perf_latency_p99:
        max: 15
```

model config
```
name: "classifier_python"

backend: "python"
max_batch_size: 12
dynamic_batching {
  preferred_batch_size: [4]
  max_queue_delay_microseconds: 3000000
}

input [
  {
    name: "image"
    data_type: TYPE_STRING
    dims: [1]
  }
]

output [
  {
    name: "result"
    data_type: TYPE_STRING
    dims: [1]
  }
]

instance_group [
  { 
     kind: KIND_GPU
  }
]
```

**Comment by rohitgr7** [comment]
with `--triton-output-path` it worked, but seems to be very slow.

**Comment by rohitgr7** [comment]
yes, that's the case.

**Comment by nv-braf** [comment]
That's very strange behavior. Can you share more details? Specifically, the container you are running in and the exact command you are using to run MA, as well as the triton output log for the passing case. And, can you confirm that the error message you are seeing is consistent when running with logging disabled.

**Comment by dyastremsky** [comment]
Closing issue due to inactivity. If you would like us to reopen this issue for follow-up, please let us know.
