### ISSUE TITLE
Not able to load models with custom plugins

### ISSUE THREAD

**Issue by alphapibeta** [triton-inference-server/model_analyzer#64]
How do we pass custom plusings to load the model in the model analyzer?

```
sudo docker run --gpus 1 --shm-size=1g --ulimit memlock=-1 --ulimit stack=67108864 -ti -v /home/ubuntu/mount-disk/sec_models/:/models -v /home/ubuntu/mount-disk/plugins/:/plugins  --env LD_PRELOAD="/plugins/libyolo_layer.so:/plugins/libdecodeplugin.so" triton_modelanalyzer bash 
```

Running the below command inside the docker

```
model-analyzer -m /models/ -n yolo1 --batch-size 1 -c 1
```
Facing this issue while running the above command

Error
```
2021-01-20 05:12:59.773 INFO[entrypoint.py:368] Triton Model Analyzer started: config={'model_repository': '/models/', 'model_names': 'yolo1', 'batch_sizes': '1', 'concurrency': '1', 'export': None, 'export_path': '.', 'filename_model_inference': 

'metrics-model-inference.csv', 'filename_model_gpu': 'metrics-model-gpu.csv', 'filename_server_only': 'metrics-server-only.csv', 'max_retries': 100, 'duration_seconds': 5.0, 'monitoring_interval': 0.01, 'client_protocol': 'grpc', 'perf_analyzer_path': 'perf_analyzer', 'perf_measurement_window': 5000, 'no_perf_output': None, 'triton_launch_mode': 

'local', 'triton_version': '20.11-py3', 'log_level': 'INFO', 'triton_http_endpoint': 'localhost:8000', 'triton_grpc_endpoint': 'localhost:8001', 'triton_metrics_url': 'http://localhost:8002/metrics', 'triton_server_path': 'tritonserver', 'triton_output_path': None, 'gpus': ['all'], 'config_file': None}
2021-01-20 05:12:59.780 INFO[entrypoint.py:94] Starting a local Triton Server...
2021-01-20 05:12:59.788 INFO[server_local.py:62] Triton Server started.
2021-01-20 05:13:00.800 INFO[entrypoint.py:209] Triton Server is ready.
2021-01-20 05:13:00.801 INFO[driver.py:236] init
2021-01-20 05:13:01.946 INFO[entrypoint.py:383] Starting perf_analyzer...
2021-01-20 05:13:01.946 INFO[analyzer.py:91] Profiling server only metrics...
2021-01-20 05:13:02.968 INFO[monitor.py:74] Using GPU(s) with UUID(s) = { GPU-5df6aea1-a690-25ee-c16e-bd46a1d95792 } for the analysis.
2021-01-20 05:13:27.431 ERROR[entrypoint.py:387] Model Analyzer encountered an error: Unable to load the model : [StatusCode.INVALID_ARGUMENT] load failed for model 'yolo1': version 1: Internal: unable to create TensorRT engine;
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/model_analyzer/triton/client/client.py", line 79, in load_model
    self._client.load_model(model.name())
  File "/usr/local/lib/python3.6/dist-packages/tritonclient/grpc/__init__.py", line 555, in load_model
    raise_error_grpc(rpc_error)
  File "/usr/local/lib/python3.6/dist-packages/tritonclient/grpc/__init__.py", line 61, in raise_error_grpc
    raise get_error_grpc(rpc_error) from None
tritonclient.utils.InferenceServerException: [StatusCode.INVALID_ARGUMENT] load failed for model 'yolo1': version 1: Internal: unable to create TensorRT engine;


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/model_analyzer/entrypoint.py", line 384, in main
    run_analyzer(config, analyzer, client, run_configs)
  File "/usr/local/lib/python3.6/dist-packages/model_analyzer/entrypoint.py", line 323, in run_analyzer
    client.load_model(model=model)
  File "/usr/local/lib/python3.6/dist-packages/model_analyzer/triton/client/client.py", line 82, in load_model
    f"Unable to load the model : {e}")
model_analyzer.model_analyzer_exceptions.TritonModelAnalyzerException: Unable to load the model : [StatusCode.INVALID_ARGUMENT] load failed for model 'yolo1': version 1: Internal: unable to create TensorRT engine;

2021-01-20 05:13:27.433 INFO[server_local.py:71] Triton Server stopped.
2021-01-20 05:13:28.251 INFO[server_local.py:80] Triton Server stopped.

```
Also, I am able to load an onnx model that doesn't require a plugin

**Comment by Tabrizian** [comment]
@alphapibeta Thanks for the report. Are you able to load the model using the Triton Inference Server alone? Can you please share the output of `tritonserver --model-repository /models/` when running inside the container? Thanks.

**Comment by alphapibeta** [comment]
@Tabrizian Yes these models are loaded and they are working.
 
**FYI, there are three models two tensorrt, that require a plugin, and one onnx, all three are working.**
Command 
```
sudo docker run --gpus all --rm --shm-size=1g --ipc=host --ulimit memlock=-1 --ulimit stack=67108864 -p8000:8000 -p8001:8001 -p8002:8002 -v/home/ubuntu/mount-disk/sec_models:/models -v/home/ubuntu/mount-disk/plugins/:/plugins --env LD_PRELOAD="/plugins/libyolo_layer.so:/plugins/libdecodeplugin.so" bdb0cbe1c039 tritonserver --model-repository=/models --grpc-infer-allocation-pool-size=16 --log-verbose 1
```

output 

```
I0120 17:37:08.985103 1 grpc_server.cc:3897] Started GRPCInferenceService at 0.0.0.0:8001
I0120 17:37:08.987942 1 http_server.cc:2705] Started HTTPService at 0.0.0.0:8000
I0120 17:37:09.030376 1 http_server.cc:2724] Started Metrics Service at 0.0.0.0:8002
```

```
curl localhost:8000/v2/models/yolo1
```

output

```
{"name":"yolo1","versions":["1"],"platform":"tensorrt_plan","inputs":[{"name":"000_net","datatype":"FP32","shape":[-1,3,608,608]}],"outputs":[{"name":"(Unnamed Layer* 506) [PluginV2IOExt]_output_0","datatype":"FP32","shape":[-1,121296,1,1]},{"name":"(Unnamed Layer* 507) [PluginV2IOExt]_output_0","datatype":"FP32","shape":[-1,30324,1,1]},{"name":"(Unnamed Layer* 508) [PluginV2IOExt]_output_0","datatype":"FP32","shape":[-1,7581,1,1]}]}
```

**Comment by alphapibeta** [comment]
#66

**Comment by Tabrizian** [comment]
Closing as the issue was resolved.
