### ISSUE TITLE
TypeError: '<' not supported between instances of 'Coordinate' and 'Coordinate'

### ISSUE THREAD

**Issue by monsterlyg** [triton-inference-server/model_analyzer#705]
profiling terminated with Trackback:
```
Traceback (most recent call last):
  File "/usr/local/bin/model-analyzer", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/model_analyzer/entrypoint.py", line 267, in main
    analyzer.profile(client=client,
  File "/usr/local/lib/python3.10/dist-packages/model_analyzer/analyzer.py", line 113, in profile
    self._profile_models()
  File "/usr/local/lib/python3.10/dist-packages/model_analyzer/analyzer.py", line 228, in _profile_models
    self._model_manager.run_models(models=[model])
  File "/usr/local/lib/python3.10/dist-packages/model_analyzer/model_manager.py", line 117, in run_models
    for run_config in rcg.get_configs():
  File "/usr/local/lib/python3.10/dist-packages/model_analyzer/config/generate/quick_plus_concurrency_sweep_run_config_generator.py", line 98, in get_configs
    yield from self._execute_quick_search()
  File "/usr/local/lib/python3.10/dist-packages/model_analyzer/config/generate/quick_plus_concurrency_sweep_run_config_generator.py", line 113, in _execute_quick_search
    yield from self._rcg.get_configs()
  File "/usr/local/lib/python3.10/dist-packages/model_analyzer/config/generate/quick_run_config_generator.py", line 126, in get_configs
    self._step()
  File "/usr/local/lib/python3.10/dist-packages/model_analyzer/config/generate/quick_run_config_generator.py", line 136, in _step
    self._take_step()
  File "/usr/local/lib/python3.10/dist-packages/model_analyzer/config/generate/quick_run_config_generator.py", line 197, in _take_step
    new_coordinate = self._neighborhood.determine_new_home()
  File "/usr/local/lib/python3.10/dist-packages/model_analyzer/config/generate/neighborhood.py", line 115, in determine_new_home
    return self._get_best_coordinate_found()
  File "/usr/local/lib/python3.10/dist-packages/model_analyzer/config/generate/neighborhood.py", line 131, in _get_best_coordinate_found
    _, best_vector = sorted(zip(measurements, vectors))[-1]
TypeError: '<' not supported between instances of 'Coordinate' and 'Coordinate'
```
maybe a bug.

**Comment by tgerdesnv** [comment]
Thanks for sharing. What version of Model Analyzer (or what release container) are you using? This looks similar to an older bug that was fixed.

**Comment by monsterlyg** [comment]
> Thanks for sharing. What version of Model Analyzer (or what release container) are you using? This looks similar to an older bug that was fixed.

I run tests in container based on nvcr.io/nvidia/tritonserver:23.05-py3 and the MA was installed by pip, because i want to use "local" launch mode.

**Comment by tgerdesnv** [comment]
Ok, this bug must still exist. We will look into it. We may reach back out for further reproduction instructions if we can't reproduce it easily.

**Comment by monsterlyg** [comment]
thanks



---Original---
From: "Timothy ***@***.***&gt;
Date: Thu, Jun 8, 2023 20:51 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [triton-inference-server/model_analyzer] TypeError: '<' notsupported between instances of 'Coordinate' and 'Coordinate' (Issue #705)




 
Ok, this bug must still exist. We will look into it. We may reach back out for further reproduction instructions if we can't reproduce it easily.

**Comment by nv-braf** [comment]
@monsterlyg, Can you rerun with verbose turned on (`model-analyzer -v profile ...`) and post the output?
Want to understand the path quick search is taking to get to this failure. Thank you.

**Comment by monsterlyg** [comment]
I've avoided the error by removing dynamic_batching because the max_batch_size is set to 0. I don't know if it is the reason. Hope this remind you of something.



---Original---
From: "Brian ***@***.***&gt;
Date: Thu, Jun 8, 2023 23:33 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [triton-inference-server/model_analyzer] TypeError: '<' notsupported between instances of 'Coordinate' and 'Coordinate' (Issue #705)




 
@monsterlyg, Can you rerun with verbose turned on (model-analyzer -v profile ...) and post the output?
 Want to understand the path quick search is taking to get to this failure. Thank you.

**Comment by monsterlyg** [comment]
> @monsterlyg, Can you rerun with verbose turned on (`model-analyzer -v profile ...`) and post the output? Want to understand the path quick search is taking to get to this failure. Thank you.

I encountered this problem again. I tried to use "-v" to get the debug output but no helpful information got.

**Comment by tgerdesnv** [comment]
Can you post the output? It would still be helpful to us.
We have a potential fix ready to go, but it would be nice to get confirmation of what is happening

**Comment by dyastremsky** [comment]
Closing issue due to inactivity. If you would to reopen this issue for follow-up, please let us know.
