### ISSUE TITLE
Quick start instructions not working

### ISSUE THREAD

**Issue by maaquib** [triton-inference-server/model_analyzer#72]
```
$ git log --format="%H" -n 1
d9cfe0dec18aaa70a760a14e06c019d4f81a3070
$ docker build . -t triton_modelanalyzer
$ docker run --gpus 1 --shm-size=1g --ulimit memlock=-1 --ulimit stack=67108864 -ti -v `pwd`/examples/quick-start:/workspace/examples triton_modelanalyzer bash
$ model-analyzer -m /workspace/examples/ -n add_sub
2021-01-26 19:15:46.221 INFO[entrypoint.py:378] Triton Model Analyzer started: config={'model_repository': '/workspace/examples/', 'model_names': ['add_sub'], 'objectives': [], 'constraints': {}, 'batch_sizes': 1, 'concurrency': 1, 'export': None, 'export_path': '.', 'filename_model_inference': 'metrics-model-inference.csv', 'filename_model_gpu': 'metrics-model-gpu.csv', 'filename_server_only': 'metrics-server-only.csv', 'max_retries': 100, 'duration_seconds': 5, 'monitoring_interval': 0.01, 'client_protocol': 'grpc', 'perf_analyzer_path': 'perf_analyzer', 'perf_measurement_window': 5000, 'no_perf_output': None, 'triton_launch_mode': 'local', 'triton_version': '20.11-py3', 'log_level': 'INFO', 'triton_http_endpoint': 'localhost:8000', 'triton_grpc_endpoint': 'localhost:8001', 'triton_metrics_url': 'http://localhost:8002/metrics', 'triton_server_path': 'tritonserver', 'triton_output_path': None, 'gpus': ['all'], 'config_file': None}
2021-01-26 19:15:46.223 INFO[entrypoint.py:91] Starting a local Triton Server...
2021-01-26 19:15:46.227 INFO[server_local.py:63] Triton Server started.
2021-01-26 19:15:47.232 INFO[entrypoint.py:207] Triton Server is ready.
2021-01-26 19:15:47.233 INFO[driver.py:236] init
2021-01-26 19:15:50.387 INFO[server_local.py:80] Triton Server stopped.
Traceback (most recent call last):
  File "/usr/local/bin/model-analyzer", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/model_analyzer/entrypoint.py", line 390, in main
    run_configs = create_run_configs(config)
  File "/usr/local/lib/python3.8/dist-packages/model_analyzer/entrypoint.py", line 237, in create_run_configs
    param_combinations = list(product(*tuple(sweep_params.values())))
TypeError: 'int' object is not iterable
```

Starting Triton inside the container works fine `tritonserver --model-repository /workspace/examples/`

**Comment by Tabrizian** [comment]
Thanks for reporting this. It should be fixed in the master.
