### ISSUE TITLE
AttributeError: 'TritonServerDocker' object has no attribute '_log_file'. Did you mean: 'log_file'?

### ISSUE THREAD

**Issue by levipereira** [triton-inference-server/model_analyzer#725]
Model analyzer return error on triton-server-23.06.

  ```
  docker run -it --gpus all  \
  -v /var/run/docker.sock:/var/run/docker.sock \
  -v /storage/triton-server/devel/triton-server-23.06/models_01:/storage/triton-server/devel/triton-server-23.06/models_01 \
  -v /storage/triton-server/devel/triton-server-23.06/model_analyzer:/storage/triton-server/devel/triton-server-23.06/model_analyzer \
  -v /storage/triton-server/devel/triton-server-23.06/model_analyzer/analysis_results:/storage/triton-server/devel/triton-server-23.06/model_analyzer/analysis_results  \
  --net=host  nvcr.io/nvidia/tritonserver:23.06-py3-sdk  
```

```
model-analyzer profile     --model-repository /storage/triton-server/devel/triton-server-23.06/models_01    \
 --profile-models  yolov7 \
--triton-launch-mode=docker     \
--output-model-repository-path /storage/triton-server/devel/triton-server-23.06/model_analyzer/output_model    \
--export-path /storage/triton-server/devel/triton-server-23.06/model_analyzer/analysis_results  \
--override-output-model-repository

[Model Analyzer] Initializing GPUDevice handles
[Model Analyzer] Using GPU 0 NVIDIA GeForce RTX 2070 SUPER with UUID GPU-3fed825f-252b-32ea-e3d7-266c45b62ce7
[Model Analyzer] WARNING: Overriding the output model repo path "/storage/triton-server/devel/triton-server-23.06/model_analyzer/output_model"
[Model Analyzer] Starting a Triton Server using docker
[Model Analyzer] No checkpoint file found, starting a fresh run.
[Model Analyzer] Profiling server only metrics...
Traceback (most recent call last):
  File "/usr/local/bin/model-analyzer", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/model_analyzer/entrypoint.py", line 267, in main
    analyzer.profile(client=client,
  File "/usr/local/lib/python3.10/dist-packages/model_analyzer/analyzer.py", line 112, in profile
    self._get_server_only_metrics(client, gpus)
  File "/usr/local/lib/python3.10/dist-packages/model_analyzer/analyzer.py", line 214, in _get_server_only_metrics
    log_file=self._server.log_file())
  File "/usr/local/lib/python3.10/dist-packages/model_analyzer/triton/server/server_docker.py", line 212, in log_file
    return self._log_file
AttributeError: 'TritonServerDocker' object has no attribute '_log_file'. Did you mean: 'log_file'?
```

**Comment by nv-braf** [comment]
Thank you for bringing this to my attention. I believe I've found the issue and have a potential workaround for you to try:

Can you set a triton output path and see if that fixes your issue? Use the `--triton-output-path`  config option. Thanks.

**Comment by levipereira** [comment]
Thank you! It worked perfectly. I really appreciate your help!
```
model-analyzer profile \
    --model-repository /storage/triton-server/devel/triton-server-23.06/models_01 \
    --profile-models yolov7 \
	--triton-launch-mode=docker \
    --output-model-repository-path /storage/triton-server/devel/triton-server-23.06/model_analyzer/model_analyzer/output_model \
	--triton-output-path  /storage/triton-server/devel/triton-server-23.06/model_analyzer/output_triton/outupt.txt   \
	--override-output-model-repository
```

**Comment by MadMenHitBooker** [comment]
Could you change the readme accordingly please ? I just found out this issue after looking into the python file.

**Comment by foocker** [comment]
> Could you change the readme accordingly please ? I just found out this issue after looking into the python file.

我发现tritonserver相关的文档和例子，好乱。 给的例子，版本都不说清楚，即使版本对了，很多参数文档也没更新，一个model_anaylzer就是如此，就没跑成功过。

**Comment by nv-braf** [comment]
This is fixed in the 23.08 release.
