### ISSUE TITLE
failed to poll from model repository

### ISSUE THREAD

**Issue by gleberof-ai** [triton-inference-server/model_analyzer#789]
I'm trying to reproduce the steps from quick start
https://github.com/triton-inference-server/model_analyzer/blob/main/docs/quick_start.md

1. pull examples
2. start docker
```
docker run -it --gpus all \
      -v /var/run/docker.sock:/var/run/docker.sock \
      -v $(pwd)/examples/quick-start:/examples/quick-start \
      --net=host nvcr.io/nvidia/tritonserver:23.10-py3-sdk
```
3. run analyzer:
```
model-analyzer profile \
    --model-repository /examples/quick-start \
    --profile-models add_sub --triton-launch-mode=docker \
    --output-model-repository-path output \
    --export-path profile_results
```

Get the following results:
```
[Model Analyzer] Initializing GPUDevice handles
[Model Analyzer] Using GPU 0 Tesla T4 with UUID GPU-0b50e773-9b7c-ac51-2d66-df4515d3f56d
[Model Analyzer] WARNING: Overriding the output model repo path "output"
[Model Analyzer] Starting a Triton Server using docker
[Model Analyzer] Loaded checkpoint from file /workspace/checkpoints/0.ckpt
[Model Analyzer] GPU devices match checkpoint - skipping server metric acquisition
[Model Analyzer] 
[Model Analyzer] Starting automatic brute search
[Model Analyzer] 
[Model Analyzer] Creating model config: add_sub_config_default
[Model Analyzer] 
[Model Analyzer] Model add_sub_config_default load failed: [StatusCode.INTERNAL] failed to load 'add_sub', failed to poll from model repository
[Model Analyzer] Saved checkpoint to /workspace/checkpoints/1.ckpt
[Model Analyzer] Creating model config: add_sub_config_0
[Model Analyzer]   Setting instance_group to [{'count': 1, 'kind': 'KIND_GPU'}]
[Model Analyzer]   Setting max_batch_size to 1
[Model Analyzer]   Enabling dynamic_batching
[Model Analyzer] 
[Model Analyzer] Model add_sub_config_0 load failed: [StatusCode.INTERNAL] failed to load 'add_sub', failed to poll from model repository
[Model Analyzer] No changes made to analyzer data, no checkpoint saved.
Traceback (most recent call last):
  File "/usr/local/bin/model-analyzer", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/model_analyzer/entrypoint.py", line 278, in main
    analyzer.profile(
  File "/usr/local/lib/python3.10/dist-packages/model_analyzer/analyzer.py", line 124, in profile
    self._profile_models()
  File "/usr/local/lib/python3.10/dist-packages/model_analyzer/analyzer.py", line 242, in _profile_models
    self._model_manager.run_models(models=[model])
  File "/usr/local/lib/python3.10/dist-packages/model_analyzer/model_manager.py", line 145, in run_models
    self._stop_ma_if_no_valid_measurement_threshold_reached()
  File "/usr/local/lib/python3.10/dist-packages/model_analyzer/model_manager.py", line 239, in _stop_ma_if_no_valid_measurement_threshold_reached
    raise TritonModelAnalyzerException(
model_analyzer.model_analyzer_exceptions.TritonModelAnalyzerException: The first 2 attempts to acquire measurements have failed. Please examine the Tritonserver/PA error logs to determine what has gone wrong.
```

I saw similar issue posted/cloed recently https://github.com/triton-inference-server/model_analyzer/issues/786

But in my case, it is not an ensemble model. It's an exact example form documentation.
And I can run a triton server with this model.

```
I1116 00:34:10.585137 1 server.cc:662] 
+---------------------------+---------+--------+
| Model                     | Version | Status |
+---------------------------+---------+--------+
| add_sub                   | 1       | READY  |
```

**Comment by nv-hwoo** [comment]
Hi, @gleberof-ai thanks for reporting this. I am able to reproduce the error and looking into the case.

**Comment by gleberof-ai** [comment]
Hi @nv-hwoo, If it helps: before that, I used to run triton locally in a container (not docker) - it was OK with version 22.04 at least—my guess - something broken to run the container in a container and to share the resources (the folder from host machine)

**Comment by nv-hwoo** [comment]
@gleberof-ai It seems like the server was not able to poll the models in the `quick-start` directory because you were mounting to `/examples/quick-start` but it is empty because we need to explicitly specify the absolute path from the host system.

If you replace the commands that resembles the steps in the quick-start guide, it will work:
1. Start MA container
```
docker run -it --gpus all \
      -v /var/run/docker.sock:/var/run/docker.sock \
      -v $(pwd)/examples/quick-start:$(pwd)/examples/quick-start \
      --net=host nvcr.io/nvidia/tritonserver:23.10-py3-sdk
```

2. Run model analyzer
```
model-analyzer profile \
    --model-repository <path-to-your-model-analyzer-repo>/examples/quick-start \
    --profile-models add_sub --triton-launch-mode=docker \
    --output-model-repository-path output \
    --export-path profile_results
```
